name: pinchme
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - click=8.2.1
  - cyrus-sasl=2.1.28
  - daiquiri=3.0.0
  - expat=2.7.3
  - greenlet=3.2.4
  - iniconfig=2.3.0
  - ld_impl_linux-64=2.44
  - libevent=2.1.12
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libkrb5=1.21.3
  - libnsl=2.0.0
  - libpq=17.6
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lmdb=0.9.31
  - ncurses=6.5
  - openldap=2.6.10
  - openssl=3.0.18
  - packaging=25.0
  - pendulum=3.1.0
  - pip=25.3
  - pluggy=1.5.0
  - psycopg2=2.9.11
  - pthread-stubs=0.3
  - pygments=2.19.2
  - pytest=8.4.2
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-json-logger=4.0.0
  - python-tzdata=2025.2
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlalchemy=1.4.51
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
prefix: /home/servilla/miniconda3/envs/pinchme
